version: "3.1"

services:
  db:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "postgres"
    volumes:
      - db_data:/var/lib/postgresql/data
  api:
    build: .
    ports:
      - "2022:2022"
    environment:
      CITY_API_DB_URL: "db"
      CITY_API_DB_PORT: "5432"
      CITY_API_DB_USER: "postgres"
      CITY_API_DB_PWD: "postgres"
      CITY_API_DB_DATABASE: "postgres"
      CITY_API_ADDR: "0.0.0.0"
    depends_on:
      - db
volumes:
  db_data: